---
driver:
  name: ec2
  aws_ssh_key_id: chef_demo_2x
  region: us-west-2
  security_group_ids: sg-e1f2c090
  subnet_id: subnet-0f591955
  associate_public_ip: true
  instance_type: c4.large ##t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Rees-Workstation"
    user: Administrator
    X-Contact: "Anthony Rees"
    X-Application: "apac"
    X-Dept: "sales"
    X-Customer: "Rees"
    X-Project: "BJC-Demo"
    X-Termination-Date: "2018-07-20T12:04:30Z"
    X-TTL: 72

transport:
    username: administrator
    ssh_key:  ~\.ssh\id_rsa
    communicator: winrm

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: windows-2016
      driver:
      image_id: ami-ba6e1bc2

suites:
  - name: workstation1
    run_list:
      - recipe[food_caravan::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: